name: AndrasFazakas
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#444051'
    - '#6c6879'
    - '#c26833'
    - '#161010'
    - '#d09074'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
