typography_spectrum: 0.6327
color:
  brandColors:
    - '#444051'
    - '#6c6879'
    - '#c26833'
    - '#161010'
    - '#d09074'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: AndrasFazakas
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
