typography_spectrum: 0.6327
color:
  brandColors:
    - '#444051'
    - '#6c6879'
    - '#c26833'
    - '#161010'
    - '#d09074'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andras Fazakas
  email: andras.fazakas@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c77db268-6ec4-48f4-8bcc-6c09eda708b4.jpg
name: Dr. Andras Fazakas
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Sjögren's syndrome
    id: 1b7b48a6-d348-4d6a-8a1d-6ce7136b045a
    type: content
  - name: Severe combined immunodeficiency
    id: fa89ebaf-43ce-4b9c-b313-fbbbeb9da9aa
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/820307d8-a065-43fe-bc38-216fc564eaa9.jpg
title: Health & Disease
description: Health is real Wealth
purpose: []
