typography_spectrum: 0.6327
color:
  brandColors:
    - '#444051'
    - '#6c6879'
    - '#c26833'
    - '#161010'
    - '#d09074'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Dr. Andras Fazakas
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Sjögren's syndrome
    id: 1b7b48a6-d348-4d6a-8a1d-6ce7136b045a
    type: content
favicon: null
purpose: []
